# Generated by Django 2.2.3 on 2020-04-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=200)),
                ('photo', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('appeared_at', models.DateTimeField(default='None')),
                ('disappeared_at', models.DateTimeField(default='None')),
                ('level', models.IntegerField(null=True)),
                ('health', models.IntegerField(null=True)),
                ('strength', models.IntegerField(null=True)),
                ('defence', models.IntegerField(null=True)),
                ('stamina', models.IntegerField(null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon')),
            ],
        ),
    ]
